cargo-features = ["profile-rustflags"]

[workspace]
members = [
    "main_backend",
    "ws_server",
    "ws_server_applications/simple_ws_server_application", "ws_server_applications/chat_ws_server_application", "chat_server",
]
resolver = "2"

[profile.dev]
opt-level = 0
rustflags = ["-Zthreads=8"]
[profile.dev.package."*"]
opt-level = 0
rustflags = ["-Zthreads=8"]

[profile.release]
lto = true
rustflags = ["-Zthreads=8"]
